[package]
name = "ballistics-analyzer"
version = "1.0.0"
edition = "2021"
authors = ["Ballistics Analyzer Contributors"]
description = "Professional ballistics calculator with hardware integration"
license = "MIT"
repository = "https://github.com/ballistics-analyzer/ballistics-analyzer"
keywords = ["ballistics", "trajectory", "shooting", "calculator", "nostr"]
categories = ["science", "simulation"]

[dependencies]
# Core GUI framework
egui = "0.28"
egui_extras = "0.28"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities with proper WASM support
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
uuid = { version = "1.10", features = ["v4", "serde", "js"] }  # js feature for WASM
rand = { version = "0.8", features = ["getrandom"] }  # getrandom for WASM
anyhow = "1.0"
thiserror = "1.0"
base64 = "0.22"

# Async runtime
futures = "0.3"

# Required for WASM random number generation
getrandom = { version = "0.2", features = ["js"] }

# Desktop-only dependencies
[target.'cfg(not(any(target_arch = "wasm32", target_os = "android")))'.dependencies]
# GUI framework for desktop
eframe = "0.28"
egui_plot = "0.28"

# Logging
env_logger = "0.11"
tracing = "0.1"

# File system and database
rusqlite = { version = "0.32", features = ["bundled"] }
rfd = "0.14"
dirs = "5.0"

# Nostr protocol
nostr-sdk = "0.35"

# Async runtime for desktop
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = "0.24"

# Image processing
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

# Clipboard support
arboard = "3.4"

# Serial port communication (for hardware)
serialport = "4.5"

# Android-specific dependencies
[target.'cfg(target_os = "android")'.dependencies]
# Use compatible version with proper feature
android-activity = { version = "0.5.2", features = ["native-activity"] }
android_logger = "0.14"
jni = "0.21"
ndk = "0.8"  # Compatible version
ndk-sys = "0.5"  # Compatible version
ndk-context = "0.1"
winit = { version = "0.29", features = ["android-native-activity"] }  # Compatible version
raw-window-handle = "0.6"

# Web/WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = { version = "0.28", default-features = false, features = ["web"] }
egui_plot = "0.28"

# WASM bindings
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

# Web APIs
web-sys = { version = "0.3.77", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "File",
    "FileList",
    "FileReader",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "Navigator",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "Storage",
    "Location",
    "History",
    "MediaQueryList",
    "Clipboard",
    "console",
] }

# Error handling and logging for WASM
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"

# Development dependencies
[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4"
tempfile = "3.12"

# Build dependencies
[build-dependencies]
# None needed currently

# Profile configurations
[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

# WASM-specific release profile
[profile.wasm-release]
inherits = "release"
opt-level = "z"  # Optimize for size
lto = "fat"
panic = "abort"

# Android-specific release profile
[profile.android-release]
inherits = "release"
opt-level = "z"
lto = true
strip = true
panic = "abort"

# Package metadata for wasm-pack
[package.metadata.wasm-pack]
"wasm-opt" = ["-Oz", "--enable-simd"]

# Android build metadata
[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
min_sdk_version = 21
target_sdk_version = 34

# Workspace configuration
[workspace]
members = ["."]
resolver = "2"

# Patches to ensure dependency compatibility
[patch.crates-io]
# Force specific versions for Android compatibility
android-activity = { version = "0.5.2", features = ["native-activity"] }

# Features for conditional compilation
[features]
default = ["desktop"]
desktop = []
web = []
android = []
hardware = []
bluetooth = []
debug-ui = []

# Library configuration
[lib]
name = "ballistics_analyzer"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# Binary configuration - only for desktop
[[bin]]
name = "ballistics-analyzer"
path = "src/main.rs"
required-features = ["desktop"]