[package]
name = "ballistics-analyzer"
version = "1.0.0"
edition = "2021"
authors = ["Ballistics Analyzer Contributors"]
description = "Professional ballistics calculator with hardware integration"
license = "MIT"
repository = "https://github.com/ballistics-analyzer/ballistics-analyzer"
keywords = ["ballistics", "trajectory", "shooting", "calculator", "nostr"]
categories = ["science", "simulation"]

[dependencies]
# Core GUI framework
eframe = "0.28"
egui = "0.28"
egui_plot = "0.28"
egui_extras = "0.28"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
base64 = "0.22"

# Async runtime (needed for some features)
futures = "0.3"

# Desktop-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Logging
env_logger = "0.11"
tracing = "0.1"

# File system and database
rusqlite = { version = "0.32", features = ["bundled"] }
rfd = "0.14"  # File dialogs
dirs = "5.0"  # Platform-specific directories

# Nostr protocol
nostr-sdk = "0.35"

# Async runtime for desktop
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = "0.24"

# Image processing
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

# Clipboard support
arboard = "3.4"

# Serial port communication (for hardware)
serialport = "4.5"

# Bluetooth support (optional, for rangefinders)
# btleplug = "0.11"  # Uncomment if you want BLE support

# Web-only dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
# WASM bindings
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

# Web APIs
web-sys = { version = "0.3.77", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "File",
    "FileList",
    "FileReader",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "Navigator",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "Storage",
    "Location",
    "History",
    "MediaQueryList",
    "Clipboard",
    "console",
] }

# Error handling and logging for WASM
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"

# JSON parsing in WASM
getrandom = { version = "0.2", features = ["js"] }

# Development dependencies
[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4"
tempfile = "3.12"

# Build dependencies
[build-dependencies]
# Add if you need build scripts

# Profile configurations
[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.wasm]
inherits = "release"
opt-level = "z"  # Optimize for size
lto = true
panic = "abort"

# Web-specific profile
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
panic = "abort"

# Package metadata for WASM
[package.metadata.wasm-pack]
"wasm-opt" = ["-Oz", "--enable-simd"]

# Workspace configuration (if you plan to have multiple crates)
[workspace]
members = ["."]
resolver = "2"

# Patch dependencies if needed
[patch.crates-io]
# Example: nostr-sdk = { git = "https://github.com/rust-nostr/nostr", branch = "master" }

# Features (optional - for conditional compilation)
[features]
default = ["desktop"]
desktop = []
web = []
hardware = []
bluetooth = []  # Add "btleplug" to dependencies if enabling this
debug-ui = []

# Library configuration
[lib]
name = "ballistics_analyzer"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# Binary configuration
[[bin]]
name = "ballistics-analyzer"
path = "src/main.rs"
required-features = ["desktop"]

# Example configurations (if you have examples)
[[example]]
name = "trajectory_calculation"
path = "examples/trajectory.rs"

# Benchmark configurations (if you have benchmarks)
[[bench]]
name = "ballistics_bench"
harness = false
path = "benches/ballistics.rs"