[package]
name = "ballistics-analyzer"
version = "0.3.0"
edition = "2021"
authors = ["Ballistics Analyzer Team"]
description = "Professional ballistics calculator with hardware integration"
repository = "https://github.com/ballistics-analyzer/ballistics-analyzer"
license = "MIT"
keywords = ["ballistics", "shooting", "trajectory", "calculator", "nostr"]

[dependencies]
# Core dependencies
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
uuid = { version = "1.6", features = ["v4", "serde", "js"] }
getrandom = { version = "0.2", features = ["js"] }

# GUI framework with web support
egui = "0.24"
eframe = { version = "0.24", default-features = false, features = ["default_fonts", "web", "persistence"] }
egui_extras = { version = "0.24", features = ["image"] }
image = { version = "0.24", features = ["jpeg", "png"] }

# Web-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "Storage",
    "Navigator",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "Notification",
    "NotificationPermission",
    "Bluetooth",
    "BluetoothDevice",
    "BluetoothRemoteGATTService",
    "Serial",
    "SerialPort",
    "File",
    "FileReader",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
] }
js-sys = "0.3"
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"

# Native dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.12"
serialport = "4.3"
btleplug = "0.11"
rusqlite = { version = "0.30", features = ["bundled", "blob"] }

# Shared dependencies with platform-specific features
nostr-sdk = { version = "0.27", default-features = false, features = ["nip07"] }
base64 = "0.21"
aes-gcm = "0.10"
argon2 = "0.5"
nalgebra = "0.32"
reqwest = { version = "0.11", features = ["json"] }

# Development dependencies
[dev-dependencies]
wasm-bindgen-test = "0.3"

# Build configuration for different targets
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.wasm-release]
inherits = "release"
opt-level = "s"

# Platform-specific features
[features]
default = ["native"]
native = ["eframe/default"]
web = ["eframe/web"]

# Required for PWA
[package.metadata.wasm-pack]
wasm-opt = ["-Os"]