[package]
name = "ballistics-analyzer"
version = "1.0.0"
edition = "2021"
authors = ["Ballistics Analyzer Contributors"]
description = "Professional ballistics calculator with hardware integration"
license = "MIT"
repository = "https://github.com/DatilDev/Ballistics-Analyzer"
keywords = ["ballistics", "trajectory", "shooting", "calculator", "nostr"]
categories = ["science", "simulation"]

[dependencies]
# Core GUI framework - using consistent versions
egui = "0.29"
egui_extras = "0.29"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities with proper WASM support
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
uuid = { version = "1.10", features = ["v4", "serde", "js"] }
rand = { version = "0.8", features = ["getrandom"] }
anyhow = "1.0"
thiserror = "1.0"
base64 = "0.22"

# Async runtime
futures = "0.3"

# Required for WASM random number generation
getrandom = { version = "0.2", features = ["js"] }

# Desktop-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# GUI framework for desktop - using latest stable version
eframe = { version = "0.29", default-features = true }
egui_plot = "0.29"

# Logging
env_logger = "0.11"
tracing = "0.1"

# File system and database
rusqlite = { version = "0.32", features = ["bundled"] }
rfd = "0.15"
dirs = "5.0"

# Nostr protocol
nostr-sdk = "0.35"

# Async runtime for desktop
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = "0.24"

# Image processing
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

# Clipboard support
arboard = "3.4"

# Serial port communication (for hardware)
serialport = "4.5"

# Web/WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
# For web, we need eframe with glow rendering
eframe = { version = "0.29", default-features = false, features = ["default_fonts", "glow"] }
egui_plot = "0.29"

# WASM bindings
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

# Web APIs
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "File",
    "FileList",
    "FileReader",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "Navigator",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "Storage",
    "Location",
    "History",
    "MediaQueryList",
    "Clipboard",
    "console",
] }

# Error handling and logging for WASM
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"

# Development dependencies
[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.4"
tempfile = "3.12"

# Profile configurations
[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.wasm]
inherits = "release"
opt-level = "z"
lto = true
panic = "abort"

# Package metadata for wasm-pack
[package.metadata.wasm-pack]
"wasm-opt" = ["-Oz", "--enable-simd"]

# Workspace configuration
[workspace]
members = ["."]
resolver = "2"

# Features for conditional compilation
[features]
default = ["desktop"]
desktop = []
web = []

# Library configuration
[lib]
name = "ballistics_analyzer"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# Binary configuration - only for desktop
[[bin]]
name = "ballistics-analyzer"
path = "src/main.rs"
required-features = ["desktop"]